# Question 1

![Question 1](HW3_Q1.png)

# Question 2

![Question 2](HW3_Q2.png)

# Question 3

- Set the matrix and calculate AAt and AtA to get the U, V matrices

In [3]:
import numpy as np
from numpy import linalg as LA

#initialize matrix A and AAt, AtA
A = np.array([[1, 0], [2, 7], [3, 5]])
AAt = A @ A.T
AtA = A.T @ A


- Get the left and right singular values by calculating the orthonormal eigenvectors for AAt and AtA
- The `LA.eig()` function not only grabs the eigenvectors but also orthonormalizes it, making U and V solvable with this function

In [4]:
#solving U
U_eigenval, U = LA.eig(AAt)

#solving V, grab the eigenvalues for sigma
V_eigenval, V = LA.eig(AtA)

- Setting up the sigma matrix
- Sort the eigenvalues by descending order, then take the square root and concat into a 3x2 matrix

In [5]:
#sort the eigenvalues and take the square root
sqrtEV = np.sqrt(sorted(V_eigenval, reverse = True))

#Store into a diagonal and add the remaining 0 rows
Sigma = np.vstack([np.diag(sqrtEV), [0, 0]])
Sigma

array([[9.25879539, 0.        ],
       [0.        , 1.50821348],
       [0.        , 0.        ]])

- Sort U and V in terms of their eigenvalues

In [6]:
U_sorted = np.argsort(-U_eigenval)
V_sorted = np.argsort(-V_eigenval)

U = U[:, U_sorted]
V = V[:, V_sorted]

In [7]:
U

array([[-0.04048486,  0.61469355, -0.78772636],
       [-0.78188419, -0.51034496, -0.35805744],
       [-0.62210778,  0.60141488,  0.50128041]])

In [8]:
V

array([[-0.37484105, -0.92708909],
       [-0.92708909,  0.37484105]])

- Thinning Step: Since $A \in \mathbb{R}^{3x2}$, cut $\Sigma \in \mathbb{R}^{2x2}$
- this implies that $U \in \mathbb{R}^{3x2}$, $V \in \mathbb{R}^{2x2}$
- To perform this, the last column of U is cut

In [9]:
U = U[:,:-1]
Sigma = Sigma[:-1, :]

- Solution:

In [14]:
print(f"U = {U}")

U = [[-0.04048486  0.61469355]
 [-0.78188419 -0.51034496]
 [-0.62210778  0.60141488]]


In [15]:
print(f"Sigma = {Sigma}")

Sigma = [[9.25879539 0.        ]
 [0.         1.50821348]]


In [16]:
print(f"V = {V}")

V = [[-0.37484105 -0.92708909]
 [-0.92708909  0.37484105]]


# Question 4

![Question 4](HW3_Q4.png)